INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Spring Roll', 800, 1, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque', 'https://i.imgur.com/SNoF6Sj.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Nacho Chips', 700, 1, 'Ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in ulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://i.imgur.com/kcoJxsy.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Guacamole', 200, 1, 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system', 'https://i.imgur.com/2Luc3Ae.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Takoyaki', 900, 1, 'Harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil', 'https://i.imgur.com/ec0xt99.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Cheese Sticks', 450, 1, 'ed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab', 'https://i.imgur.com/8gaWh47.jpg');

INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Chimichanga', 1299, 2, 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://i.imgur.com/vwdKrkf.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Empanada', 1650, 2, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque', 'https://i.imgur.com/4Xl55PH.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Mushroom Quesadilla', 1300, 2, 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.', 'https://i.imgur.com/G61LLEB.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Fish Ceviche', 999, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://i.imgur.com/TlrPaCc.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Pork Taco', 1050, 2, 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.', 'https://i.imgur.com/quehDVt.jpg');

INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Beef Tendon Pho', 1299, 3, 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.', 'https://i.imgur.com/eJNFWcV.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Chicken Pho', 1299, 3, 'perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa', 'https://i.imgur.com/7pPR2nk.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Bun Cha', 1299, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', 'https://i.imgur.com/8xNEFg7.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Pork Vermiceli', 1299, 3, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque', 'https://i.imgur.com/d5kFpam.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Pork Pho', 1299, 3, 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://i.imgur.com/rQV0Ir8.jpg');

INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Pho Taco', 800, 4, 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://i.imgur.com/9PnSlrF.png');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Kimchi Poutine', 1799, 4, 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system', 'https://i.imgur.com/n9Nv58J.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Chocolate Ramen', 2000, 4, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque', 'https://i.imgur.com/RKzni9I.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Penguin Sushi', 2000, 4, 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?', 'https://i.imgur.com/oWhgAFw.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Apple iPad', 50000, 4, 'But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences', 'https://i.imgur.com/IjIOiFW.jpg');

INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Fried Banana', 399, 5, 'cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. ', 'https://i.imgur.com/yGsDe2m.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Ice Cream', 200, 5, 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque', 'https://i.imgur.com/KyJJihG.jpg');

INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Pepsi', 300, 6, 'sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.', 'https://i.imgur.com/lHdLs77.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Sprite', 300, 6, 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?', 'https://i.imgur.com/3ofZuUG.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Heineken', 599, 6, 'quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor', 'https://i.imgur.com/tr7BPwM.png');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Apple Juice', 299, 6, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque', 'https://i.imgur.com/wGrYhFF.jpg');
INSERT INTO menu_items (name, price, category_id, description, photo_url) VALUES ('Strong Zero', 500, 6, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque', 'https://i.imgur.com/RvmcBwy.jpg');
